name: Deploy Agrogestor API


on:

  push:

    branches:
      - main



jobs:


  deploy:


    runs-on: self-hosted



    steps:


      - name: Verificar ambiente da VM

        run: |

          echo "===== SISTEMA ====="

          whoami

          uname -a


          echo "===== DOCKER ====="

          docker --version

          docker compose version


          echo "===== MEMORIA ====="

          free -h


          echo "===== DISCO ====="

          df -h


          echo "===== DOCKER USO ====="

          docker system df





      - name: Atualizar projeto na VM

        run: |

          cd /srv/apps


          if [ ! -d "agrogestor-api" ]; then

            git clone https://github.com/ALVAROVELAME/agrogestor-api.git

          fi


          cd agrogestor-api


          git fetch origin main

          git reset --hard origin/main


          echo "Projeto atualizado"





      - name: Validar estrutura do projeto

        run: |

          cd /srv/apps/agrogestor-api


          test -f Dockerfile

          test -f docker-compose.yml

          test -f pom.xml


          echo "Arquivos principais encontrados"





      - name: Verificar container atual

        run: |

          docker ps


          if docker inspect agrogestor_api >/dev/null 2>&1

          then

            echo "Container atual encontrado"

          else

            echo "Primeira instalação"

          fi





      - name: Parar versão antiga

        run: |

          cd /srv/apps/agrogestor-api


          docker compose down || true





      - name: Construir nova imagem usando cache

        run: |

          cd /srv/apps/agrogestor-api


          docker compose build --pull





      - name: Subir nova versão

        run: |

          cd /srv/apps/agrogestor-api


          docker compose up -d --remove-orphans





      - name: Aguardar inicialização

        run: |

          echo "Aguardando Spring Boot iniciar..."

          sleep 25





      - name: Verificar aplicação

        run: |

          echo "===== CONTAINERS ====="

          docker ps


          echo "===== LOGS API ====="

          docker logs --tail 100 agrogestor_api





      - name: Verificar consumo

        run: |

          docker stats --no-stream





      - name: Limpeza segura

        run: |

          docker image prune -f


          echo "Limpeza concluída"
